language: go
go:
  - 1.7.x
  - master
before_install:
  - go get github.com/mattn/goveralls
script: 
  - goveralls -v -service travis-ci -repotoken PAnRlrFKQAlk5Kq0wlfSCcoJJz1hlSRkz
notifications:
  recipients:
    - henson.lu@gmail.com
  email:
    on_success: change
    on_failure: always